# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use a bog-standard Ubuntu 12.04 LTS Server.
  config.vm.box = "precise32"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-i386-vagrant-disk1.box"

  # Share the top-level directory of the project with the VM.
  config.vm.synced_folder "../../", "/home/vagrant/lvmraid5"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  #
  # View the documentation for the provider you're using for more
  # information on available options.
  #
  # For now this vagrant file only supports VirtualBox.
  config.vm.provider :virtualbox do |vb|
    # Create and attach disk images.
    ii = 1
    [160, 160, 320, 320, 750, 750, 1500, 1500].each do |size|
      unless File.exist?("lvmraid5_drive_#{ii}.vdi")
        vb.customize ['createhd', '--filename', "lvmraid5_drive_#{ii}", '--size', size]
      end
      vb.customize ['storageattach', :id, '--storagectl', 'SATAController', '--port', ii, '--device', 0, '--type', 'hdd', '--medium', "lvmraid5_drive_#{ii}.vdi"]
      ii = ii + 1
    end
  end

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file base.pp in the manifests_path directory.
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "default.pp"
  end
end
