# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use a bog-standard Ubuntu 12.04 LTS Server.
  config.vm.box = "precise32"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-i386-vagrant-disk1.box"

  # Share the top-level directory of the project with the VM.
  config.vm.synced_folder "../../", "/home/vagrant/lvmraid5"

  # For now this vagrant file only supports VirtualBox.
  config.vm.provider :virtualbox do |vb|
    ii = 1
    [160, 160, 320, 320, 750, 750, 1500, 1500, 2000, 2000].each do |size|
      # If we don't yet have this virtual disk image, create it.
      unless File.exist?("lvmraid5_drive_#{ii}.vdi")
        vb.customize ['createhd', '--filename', "lvmraid5_drive_#{ii}", '--size', size]
      end
      # Tell VirtualBox to attach the disk image to this VM.
      vb.customize ['storageattach', :id, '--storagectl', 'SATAController', '--port', ii, '--device', 0, '--type', 'hdd', '--medium', "lvmraid5_drive_#{ii}.vdi"]
      ii = ii + 1
    end
  end

  # Enable provisioning with Puppet stand alone.
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "default.pp"
  end
end
